apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: myorg/auth-service:1.2
        ports:
        - containerPort: 8082
